name: codegopay
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  page_transition: ^2.1.0
  bloc: ^8.1.2
  flutter_bloc: 8.1.6
  dio: ^5.3.3
  http: ^1.2.0
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.0.0
  country_picker: ^2.0.21
  intl: ^0.19.0
  flutter_spinkit: ^5.2.0
  connectivity_plus: ^5.0.0
  flutter_slidable: ^3.0.0
  firebase_messaging: 15.1.0
  curved_navigation_bar: ^1.0.3
  cloud_firestore: 5.4.0
  camera: 0.11.0+2
  intl_phone_field: ^3.1.0
  permission_handler: ^11.0.1
  device_info_plus: ^10.1.2
  local_auth: ^2.1.7
  url_launcher: 6.3.0
  image_picker: 1.1.2
  slidable_button: ^3.0.0+1
  awesome_card: ^1.1.7
  sleek_circular_slider: ^2.0.1
  path_provider: ^2.1.4
  #  flutter_face_core: ^5.2.0
  screenshot: 3.0.0
  share_plus: ^8.0.3
  barcode_scan2: ^4.3.0
  flutter_face_api: 6.2.3
  package_info_plus: 8.0.2
  location: 7.0.0
  geolocator: ^12.0.0
#  store_redirect: any
  firebase_core: 3.4.0
  image: ^4.1.7
  flutter_toggle_tab: ^1.4.1
  dart_ipify: ^1.1.1
  webview_flutter: 4.9.0
  dropdown_textfield: ^1.2.0
  seon_sdk_flutter_plugin: 1.0.1
  flutter_idensic_mobile_sdk_plugin: ^1.32.1
  syncfusion_flutter_signaturepad: 27.1.51
  syncfusion_flutter_gauges: 27.1.51
  country_code_picker: ^3.0.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1

  #notifications:
  delightful_toast: ^1.1.0
  awesome_dialog: ^3.1.0

dependency_overrides:
  flutter_face_core_basic: 6.3.152

dev_dependencies:
  #  flutter_launcher_icons: ^0.13.1


  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to321`
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: 5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gifs/
    - assets/images/dashboard-notification.png
    - assets/images/error.png
    - assets/images/img.png
    - assets/logo/
    - assets/svg/
    - assets/svg/add-people.svg
    - assets/svg/alert-icon.svg
    - assets/svg/arrow-down-left.svg
    - assets/svg/arrow-exchange.svg
    - assets/svg/arrow-up-right.svg
    - assets/svg/bell.svg
    - assets/svg/biometric.svg
    - assets/svg/buy.svg
    - assets/svg/card-add.svg
    - assets/svg/cards.svg
    - assets/svg/clock-rewind.svg
    - assets/svg/close-black.svg
    - assets/svg/close.svg
    - assets/svg/contact-us.svg
    - assets/svg/copy.svg
    - assets/svg/currency-arrow.svg
    - assets/svg/daily-profit.svg
    - assets/svg/deposit.svg
    - assets/svg/dialog-warning.svg
    - assets/svg/error-icon.svg
    - assets/svg/forgot-password.svg
    - assets/svg/gift-cards.svg
    - assets/svg/home.svg
    - assets/svg/investment.svg
    - assets/svg/light.svg
    - assets/svg/location.svg
    - assets/svg/lock.svg
    - assets/svg/logout.svg
    - assets/svg/menu.svg
    - assets/svg/month-profit.svg
    - assets/svg/no-card.svg
    - assets/svg/no-notification.svg
    - assets/svg/no-transaction.svg
    - assets/svg/notification-bell.svg
    - assets/svg/review-transaction.svg
    - assets/svg/security-user.svg
    - assets/svg/sell.svg
    - assets/svg/send.svg
    - assets/svg/setting.svg
    - assets/svg/shield-dollar.svg
    - assets/svg/stak.svg
    - assets/svg/success-dialog.svg
    - assets/svg/success-icon.svg
    - assets/svg/total-amount.svg
    - assets/svg/total-profit.svg
    - assets/svg/transaction-icon.svg
    - assets/svg/wallet.svg
    - assets/svg/warning.svg
    - assets/svg/withdraw.svg
    - assets/videos/
    - images/
    - images/card/
    - images/icon/
    - images/investment/
    - images/kyc/
    - images/svg/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.otf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
