/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'codegopay';
  static const String PLUGIN_VERSION = '2.0.0+1';
  static const String IMG_1 = 'assets/images/img_1.png';
  static const String SUCCESS_DIALOG = 'assets/images/success-dialog.png';
  static const String ERROR_DIALOG = 'assets/svg/error-dialog.svg';
  static const String WARNING_DIALOG = 'assets/svg/warning-dialog.svg';
}
