/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'codegopay';
  static const String PLUGIN_VERSION = '2.0.0+1';
  static const String DASHBOARD_NOTIFICATION = 'assets/images/dashboard-notification.png';
  static const String ERROR = 'assets/images/error.png';
  static const String IMG = 'assets/images/img.png';
  static const String ADD_PEOPLE = 'assets/svg/add-people.svg';
  static const String ALERT_ICON = 'assets/svg/alert-icon.svg';
  static const String ARROW_DOWN_LEFT = 'assets/svg/arrow-down-left.svg';
  static const String ARROW_EXCHANGE = 'assets/svg/arrow-exchange.svg';
  static const String ARROW_UP_RIGHT = 'assets/svg/arrow-up-right.svg';
  static const String BELL = 'assets/svg/bell.svg';
  static const String BIOMETRIC = 'assets/svg/biometric.svg';
  static const String BUY = 'assets/svg/buy.svg';
  static const String CARD_ADD = 'assets/svg/card-add.svg';
  static const String CARDS = 'assets/svg/cards.svg';
  static const String CLOCK_REWIND = 'assets/svg/clock-rewind.svg';
  static const String CLOSE_BLACK = 'assets/svg/close-black.svg';
  static const String CLOSE = 'assets/svg/close.svg';
  static const String CONTACT_US = 'assets/svg/contact-us.svg';
  static const String COPY = 'assets/svg/copy.svg';
  static const String CURRENCY_ARROW = 'assets/svg/currency-arrow.svg';
  static const String DAILY_PROFIT = 'assets/svg/daily-profit.svg';
  static const String DEPOSIT = 'assets/svg/deposit.svg';
  static const String DIALOG_WARNING = 'assets/svg/dialog-warning.svg';
  static const String ERROR_ICON = 'assets/svg/error-icon.svg';
  static const String GIFT_CARDS = 'assets/svg/gift-cards.svg';
  static const String HOME = 'assets/svg/home.svg';
  static const String INVESTMENT = 'assets/svg/investment.svg';
  static const String LIGHT = 'assets/svg/light.svg';
  static const String LOCATION = 'assets/svg/location.svg';
  static const String LOCK = 'assets/svg/lock.svg';
  static const String LOGOUT = 'assets/svg/logout.svg';
  static const String MENU = 'assets/svg/menu.svg';
  static const String MONTH_PROFIT = 'assets/svg/month-profit.svg';
  static const String NO_CARD = 'assets/svg/no-card.svg';
  static const String NO_NOTIFICATION = 'assets/svg/no-notification.svg';
  static const String NO_TRANSACTION = 'assets/svg/no-transaction.svg';
  static const String NOTIFICATION_BELL = 'assets/svg/notification-bell.svg';
  static const String REVIEW_TRANSACTION = 'assets/svg/review-transaction.svg';
  static const String SECURITY_USER = 'assets/svg/security-user.svg';
  static const String SELL = 'assets/svg/sell.svg';
  static const String SEND = 'assets/svg/send.svg';
  static const String SETTING = 'assets/svg/setting.svg';
  static const String SHIELD_DOLLAR = 'assets/svg/shield-dollar.svg';
  static const String STAK = 'assets/svg/stak.svg';
  static const String SUCCESS_DIALOG = 'assets/svg/success-dialog.svg';
  static const String SUCCESS_ICON = 'assets/svg/success-icon.svg';
  static const String TOTAL_AMOUNT = 'assets/svg/total-amount.svg';
  static const String TOTAL_PROFIT = 'assets/svg/total-profit.svg';
  static const String TRANSACTION_ICON = 'assets/svg/transaction-icon.svg';
  static const String WALLET = 'assets/svg/wallet.svg';
  static const String WARNING = 'assets/svg/warning.svg';
  static const String WITHDRAW = 'assets/svg/withdraw.svg';
}
