/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class ImagesRes {
  ImagesRes._();

  static const String PLUGIN_NAME = 'codegopay';
  static const String PLUGIN_VERSION = '2.0.0+1';
  static const String T_ICON = 'images/investment/t_icon.png';
}
