// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6L9ZOzEBHK0N41OHCdqGpOPx6AijsmwQ',
    appId: '1:830718645903:web:9d6ca5f59cf467345e82fa',
    messagingSenderId: '830718645903',
    projectId: 'codegopay',
    authDomain: 'codegopay.firebaseapp.com',
    storageBucket: 'codegopay.appspot.com',
    measurementId: 'G-JRBKPCL9Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8nEC3xRLw-zFBL1kuBPkHulxSYALb3o',
    appId: '1:830718645903:android:298b58a6dd7dbd615e82fa',
    messagingSenderId: '830718645903',
    projectId: 'codegopay',
    storageBucket: 'codegopay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS_QjFiUNuWhwJmSclYJFnyaa6NitpLC4',
    appId: '1:830718645903:ios:21dc13f48aaa99bb5e82fa',
    messagingSenderId: '830718645903',
    projectId: 'codegopay',
    storageBucket: 'codegopay.appspot.com',
    iosBundleId: 'com.codegopay.individual',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS_QjFiUNuWhwJmSclYJFnyaa6NitpLC4',
    appId: '1:830718645903:ios:a638890ff2bd167e5e82fa',
    messagingSenderId: '830718645903',
    projectId: 'codegopay',
    storageBucket: 'codegopay.appspot.com',
    iosBundleId: 'com.codegopay.individual.RunnerTests',
  );
}